language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
# install:
#  - pip install mpmath
# command to run tests
script: python rollingshutter.py images 1 png 250 250
